# AUTOGENERATED! DO NOT EDIT! File to edit: 02_mains.ipynb (unless otherwise specified).

__all__ = ['run_de_dim', 'run_fc_rename', 'run_merge_fc_deseq2', 'run_polya']

# Cell

import defopt
from .pipelines import de_dimensions
from .preprocess import featurecount_rename
from .merge.degfc import merge_fc_deseq2
from .nanopore import polya_length_correlation

# Cell


def run_de_dim():
    defopt.run(de_dimensions)

def run_fc_rename():
    defopt.run(featurecount_rename)

def run_merge_fc_deseq2():
    defopt.run(merge_fc_deseq2)

def run_polya():
    defopt.run(polya_length_correlation)