# AUTOGENERATED! DO NOT EDIT! File to edit: 02_mains.ipynb (unless otherwise specified).

__all__ = ['run_de_dim', 'run_fc_rename']

# Cell

import defopt
from .pipelines import de_dimensions
from .preprocess import featurecount_rename

# Cell


def run_de_dim():
    defopt.run(de_dimensions)

def run_fc_rename():
    defopt.run(featurecount_rename)