# AUTOGENERATED! DO NOT EDIT! File to edit: 02_mains.ipynb (unless otherwise specified).

__all__ = ['run_de_dim']

# Cell

import defopt
from .pipelines import de_dimensions

# Cell


def run_de_dim():
    defopt.run(de_dimensions)