# AUTOGENERATED! DO NOT EDIT! File to edit: 02_mains.ipynb (unless otherwise specified).

__all__ = ['run_main']

# Cell

import defopt
from bitk.pipelines import de_dimensions,scatter_plot
from bitk.preprocess import featurecount_rename
from bitk.merge.degfc import merge_fc_deseq2
from bitk.nanopore import polya_length_correlation
from bitk.utils.bamfilter import filter_bam_by_name
from bitk.bam.reads import extract_sequences

# Cell


def run_main():
    defopt.run([de_dimensions,
                featurecount_rename,
                merge_fc_deseq2,
                polya_length_correlation,
                scatter_plot,
                filter_bam_by_name,
                extract_sequences
                ])

